name: "Helm deployer action on EKS"
description: "Authenticates on EKS clusters and executes Helm commands. Can also be used with kubectl commands."
branding:
  icon: 'anchor'  
  color: 'blue'
inputs:
  aws-region:
    description: 'AWS region to use (default: eu-west-2)'
    required: true
    default: eu-west-2
  cluster-name:
    description: 'EKS cluster name.'
    required: true
  command:
    description: "Your command (kubectl or helm)"
    required: true
outputs:
  result:
    description: "Output returned by your Helm or kubectl command"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    AWS_REGION: ${{ inputs.aws-region }}
    CLUSTER_NAME: ${{ inputs.cluster-name }}
  args:
    - ${{ inputs.command }}